---
javascripts:
- base:
  - prototype
  - effects
  - dragdrop
  - controls
  - application
  - fckeditor/fckeditor
stylesheets:
- base:
  - default
  - ui.all
- admin:
  - default
  - admin
- dialog:
  - dialog
