# Configuration options can be accessed as
#   configatron.site_name

development: &local
    site_name: D2 Leads
    site_url: www.d2leads.com

    company_name: D2 Leads
    admin_email: support@d2leads.com

    support_name: D2 Leads
    support_email: support@d2leads.com

production:
  <<: *local

staging:
  <<: *local

test:
  <<: *local

