# Configuration options can be accessed as
#   configatron.site_name

development: &local
    site_name: Quick Data Robot
    site_url: www.qdrllc.com
    
    company_name: Quick Data Robot
    admin_email: support@qdrllc.com
    
    support_name: QDRobot Support
    support_email: support@qdrllc.com

production:
  <<: *local
  
staging:
  <<: *local

test:
  <<: *local
