# Configuration options can be accessed as
#   configatron.site_name

development: &local
    site_name: Quick Data Robot
    site_url: www.newcarvalet.com:3000
    
    company_name: Quick Data Robot
    admin_email: qdrobot@isiritech.net
    
    support_name: Quick Data Robot
    support_email: qdrobot@isiritech.net

production:
  <<: *local
  
staging:
  <<: *local

test:
  <<: *local
