development:
  type: pop
  server: mail.isiritech.net
  username: qdrobot@isiritech.net
  password: qdrobot

development1:
  type: pop
  server: mail.qdrobot.com
  username: qd1@qdrobot.com
  password: password01
  
test:
  type: pop
  server: localhost
  username: username
  password: password
  
production:
  type: pop
  server: mail.isiritech.net
  username: qdrobot@isiritech.net
  password: qdrobot
